FROM node:21-alpine3.18

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
COPY .npmrc ./

RUN ls -a
RUN npm install && npm install -g nodemon

COPY src ./src


EXPOSE 4003

CMD ["npm","run", "dev"]
